repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: double-quote-string-fixer
        stages:
          - commit
          - push
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
        stages:
          - commit
          - push
  - repo: local
    hooks:
      - id: prospector
        name: prospector
        entry: ./prospector.sh
        language: script
        #        files and args won't work. Use prospector.sh to set them.
        files: .py$  # set files to minimize checks
        stages:
          - commit
          - push
