FROM python:3.7-slim

RUN apt-get update && apt-get install -y apt-utils gcc g++

WORKDIR /usr/src/app

COPY wait-for-it.sh ./

COPY requirements*.txt ./

RUN pip install -r requirements-dev.txt

COPY application/ ./application/

ENV PYTHONPATH=:/usr/src/app
